FROM lsstts/robot:latest
LABEL org.opencontainers.image.authors="trekkie2@gmail.com"
ARG USER=saluser
ARG HOME=/home/${USER}

USER root
WORKDIR /

RUN mkdir /root/.aws
ADD aws_config /root/.aws/config
ADD lv_includes.tgz /
ADD mavenrepo69.tgz /root
ADD mavenrepo69.tgz ${HOME}
ADD settings.xml ${HOME}/.m2
RUN chown -R 73006:73006 ${HOME}/.m2 

# AWS CLI
RUN python3.11 -m pip install awscli --upgrade

# Install packages and dependencies
RUN dnf -y install tk tk-devel \
ncurses-libs xterm \
xorg-x11-fonts-misc \
gnome-terminal iproute \
mariadb make gcc-c++ \
rpm-build && \
dnf clean all && \
rm -rf /var/cache/dnf

# Maven
ADD maven.sh /etc/profile.d/
RUN wget -P /tmp https://mirrors.gigenet.com/apache/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz
RUN tar xf /tmp/apache-maven-3.9.8-bin.tar.gz -C /opt && \
ln -s /opt/apache-maven-3.9.8 /opt/maven

# OpenSplice
ADD OpenSpliceDDS-6.10.4-2.el8.x86_64.rpm /tmp
RUN dnf install -y /tmp/OpenSpliceDDS-6.10.4-2.el8.x86_64.rpm
RUN rm /tmp/OpenSpliceDDS-6.10.4-2.el8.x86_64.rpm

# Setup environment
USER ${USER}

COPY --chown=73006:73006 start.sh ${HOME}/.
COPY --chown=73006:73006 rpmmacros ${HOME}/.rpmmacros
COPY --chown=0:0 rpmmacros /root/.rpmmacros

# Set safe.directory
RUN git config --global --add safe.directory ${HOME}/repos/ts_sal && git config --global --add safe.directory ${HOME}/repos/ts_xml

# System EnvVars
ENV MAVEN_HOME=/opt/maven
ENV M2_HOME=${MAVEN_HOME}
ENV PATH=${MAVEN_HOME}/bin:${PATH}

# SAL/XML EnvVars
ENV LSST_SDK_INSTALL=$HOME/repos/ts_sal
ENV OSPL_HOME=/opt/OpenSpliceDDS/V6.10.4/HDE/x86_64.linux
ENV LSST_DDS_DOMAIN=citest

RUN echo "" >> ${HOME}/.bash_profile && \
echo 'source /etc/profile.d/maven.sh' >> ${HOME}/.bash_profile && \
echo 'source $LSST_SDK_INSTALL/setup.env' >> ${HOME}/.bash_profile && \
echo 'export TS_XML_DIR=${HOME}/repos/ts_xml' >> ${HOME}/.bash_profile

ENV LSST_DDS_PARTITION_PREFIX=citest
